# Generated by Django 6.0.2 on 2026-06-23 10:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=64, unique=True)),
                ('label', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('text', 'Texte'), ('number', 'Nombre'), ('bool', 'Booléen'), ('select', 'Liste de choix')], default='text', max_length=10)),
                ('options', models.JSONField(blank=True, default=list, help_text='Pour type=select : liste des valeurs autorisées')),
                ('is_localizable', models.BooleanField(default=False, help_text='True = une valeur par langue (ex: descriptif)')),
            ],
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='FamilyAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_required', models.BooleanField(default=False)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freshpim.attribute')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freshpim.family')),
            ],
            options={
                'unique_together': {('family', 'attribute')},
            },
        ),
        migrations.AddField(
            model_name='family',
            name='attributes',
            field=models.ManyToManyField(related_name='families', through='freshpim.FamilyAttribute', to='freshpim.attribute'),
        ),
        migrations.CreateModel(
            name='PIMProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('in_review', 'En validation'), ('published', 'Publié'), ('archived', 'Archivé')], default='draft', max_length=15)),
                ('completeness', models.PositiveSmallIntegerField(default=0, help_text='% attributs obligatoires remplis')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pim_products_created', to=settings.AUTH_USER_MODEL)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='freshpim.family')),
            ],
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('image', 'Image'), ('video', 'Vidéo'), ('pdf', 'PDF')], default='image', max_length=10)),
                ('url', models.URLField(max_length=500)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='freshpim.pimproduct')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locale', models.CharField(default='fr', max_length=5)),
                ('value', models.TextField()),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freshpim.attribute')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_values', to='freshpim.pimproduct')),
            ],
            options={
                'unique_together': {('product', 'attribute', 'locale')},
            },
        ),
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locale', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=200)),
                ('marketing_description', models.TextField(blank=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='freshpim.pimproduct')),
            ],
            options={
                'unique_together': {('product', 'locale')},
            },
        ),
    ]
