# Generated by Django 6.0.2 on 2026-03-11 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('role', models.CharField(default='user', max_length=100)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(default='', max_length=200)),
                ('last_connection', models.DateField(auto_now_add=True)),
                ('last_modification', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
