# Generated by Django 6.0.2 on 2026-03-19 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='discount_at_sale',
            field=models.IntegerField(default=0),
        ),
    ]
