# Generated by Django 6.0.2 on 2026-03-15 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_category_manufacturer_retailer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManufacturerArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(max_length=5)),
                ('availability', models.BooleanField(default=True)),
                ('sales', models.BooleanField(default=False)),
                ('comments', models.TextField()),
                ('manufacturer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.manufacturer')),
                ('prod_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product')),
            ],
        ),
        migrations.AlterField(
            model_name='retailerarticle',
            name='tig_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.manufacturerarticle'),
        ),
        migrations.DeleteModel(
            name='ManufactureArticle',
        ),
    ]
