# Generated by Django 6.0.2 on 2026-06-23 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_sale_discount_at_sale'),
        ('freshpim', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturer',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='product',
            name='pim_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='freshpilot_products', to='freshpim.pimproduct'),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='utilisateur', to='app.manufacturer'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('ROLE_USER', 'Utilisateur'), ('ROLE_ADMIN', 'Admin retailer'), ('ROLE_SUPPLIER', 'Fournisseur'), ('ROLE_PIM_ADMIN', 'Admin PIM')], default='ROLE_USER', max_length=100),
        ),
    ]
