# Generated by Django 6.0.2 on 2026-06-23 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_manufacturer_email_product_pim_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('ROLE_USER', 'Utilisateur'), ('ROLE_ADMIN', 'Admin retailer'), ('ROLE_MANUFACTURER', 'Fournisseur'), ('ROLE_PIM_ADMIN', 'Admin PIM')], default='ROLE_USER', max_length=100),
        ),
    ]
