# Generated by Django 6.0.2 on 2026-03-15 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_manufacturerarticle_alter_retailerarticle_tig_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturerarticle',
            name='sales',
            field=models.IntegerField(default=0),
        ),
    ]
