# Generated by Django 6.0.2 on 2026-03-15 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_manufacturerarticle_sales'),
    ]

    operations = [
        migrations.AddField(
            model_name='retailer',
            name='id_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.utilisateur'),
            preserve_default=False,
        ),
    ]
