# Generated by Django 6.0.2 on 2026-03-16 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_retailer_id_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manufacturerarticle',
            old_name='manufacturer_id',
            new_name='manufacturer',
        ),
        migrations.RenameField(
            model_name='purchase',
            old_name='id_retailer_article',
            new_name='retailer_article',
        ),
        migrations.RenameField(
            model_name='retailerarticle',
            old_name='id_retail',
            new_name='retail',
        ),
        migrations.RenameField(
            model_name='retailerarticle',
            old_name='tig_id',
            new_name='tig',
        ),
        migrations.RenameField(
            model_name='sale',
            old_name='id_retailer_article',
            new_name='retailer_article',
        ),
        migrations.RemoveField(
            model_name='retailer',
            name='id_user',
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='retailer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.retailer'),
            preserve_default=False,
        ),
    ]
